### ISSUE TITLE
Prevent notification sound on android?

### ISSUE THREAD

**Issue by nowrap** [preterive/cordova-music-controls-plugin#2]
Hello,
when the MusicController is created on android i can hear a notification sound.
Can this be prevented?

Regards
nowrap

**Comment by preterive** [comment]
which Android version do you use? There should be no sound.

**Comment by preterive** [comment]
Should be fixed now. Please try and give feedback.

**Comment by nowrap** [comment]
Thx alot!
I try to test it until next tuesday, maybe on the weekend.

We are using different devices with there stock rom versions. So it's mainly android 6, 7 and 8.
After the testing i can provide more details.
